{% set name = "raphtory" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Pometry/Raphtory/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f99caa183387c68a3cdc0949c9000c23553cb3f33524989fa14170a3f522f69d

build:
  number: 0
  script: {{ PYTHON }} -m pip install ./python -vv --no-deps --no-build-isolation
  # gql-with-all not on s390x
  skip: True  # [py<38 or s390x]

requirements:
  build:
    - cmake
    - protobuf
    - {{ compiler("rust") }}
  host:
    - python
    - pip
    - maturin >=1.4.0
  run:
    - python
    - pyvis >=0.3.2
    - networkx >=2.6.3
    - pandas >=2.0.3
    - pyarrow >=14.0.1,<16
    - requests >=2.31.0
    - gql-with-all ==3.5.0
    - matplotlib-base >=3.4.3
    - ipywidgets >=8.1.5

test:
  imports:
    - raphtory
    - raphtory.algorithms
    - raphtory.graph_gen
    - raphtory.graph_loader
    - raphtory.graphql
    - raphtory.vectors
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://www.raphtory.com
  summary: Raphtory is an in-memory graph tool written in Rust with friendly Python APIs on top
  description: |
    Raphtory is an in-memory graph tool written in Rust with friendly Python APIs on top. 
    It is blazingly fast, scales to hundreds of millions of edges on your laptop, and can be dropped into your 
    existing pipelines with a simple pip install raphtory.
    It supports time traveling, multilayer modelling, and advanced analytics beyond simple querying like 
    community evolution, dynamic scoring, and mining temporal motifs.
  license: GPL-3.0
  license_family: GPL3
  license_file: LICENSE
  dev_url: https://github.com/pometry/raphtory
  doc_url: https://docs.raphtory.com

extra:
  recipe-maintainers:
    - msentissi
